sudo: false

language: python

matrix:
  include:
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.7
      dist: xenial
      sudo: true
    - python: nightly
      dist: trusty
      sudo: false
  # Ignore failures for unstable versions
  allow_failures:
    - python: nightly

install:
  - make init
  - python -m pip install -e .

before_script:
  - make lint

script:
  - make test

after_success:
  - coveralls

deploy:
  provider: pypi
  user: cmccandless
  password: $PYPI_PASSWORD
  on:
    branch: master
    tags: true
    distributions: sdist bdist_wheel
    repo: cmccandless/exutil
    python: '3.7'
